const loginPage = require('../pageobjects/login.page')
const inventoryPage = require('../pageobjects/inventory.page')

describe('Footer links', () => {
    it('Footers should work properly', async () => {
        await loginPage.open()
        await loginPage.inputUsername.addValue('standard_user')
        await loginPage.inputPassword.addValue('secret_sauce')
        await loginPage.btnLogin.click()
        await inventoryPage.btnTwitter.scrollIntoView()
        await inventoryPage.btnTwitter.click()
        await browser.switchWindow('https://twitter.com/saucelabs')
        await expect(browser).toHaveUrl('https://twitter.com/saucelabs')
        await browser.switchWindow('https://www.saucedemo.com/inventory.html')
        await expect(browser).toHaveUrl('https://www.saucedemo.com/inventory.html')
        await inventoryPage.btnFB.click()
        await browser.switchWindow('https://www.facebook.com/saucelabs')
        await expect(browser).toHaveUrl('https://www.facebook.com/saucelabs')
        await browser.switchWindow('https://www.saucedemo.com/inventory.html')
        await expect(browser).toHaveUrl('https://www.saucedemo.com/inventory.html')
        await inventoryPage.btnLI.click()
        await browser.switchWindow('https://www.linkedin.com/company/sauce-labs/')
        await expect(browser).toHaveUrl('https://www.linkedin.com/company/sauce-labs/')
    })
})