const loginPage = require('../pageobjects/login.page')
const inventoryPage = require('../pageobjects/inventory.page')
const cartPage = require('../pageobjects/cart.page')
const checkoutPage = require('../pageobjects/checkout.page')
const checkoutPage2 = require('../pageobjects/checkout.page2')
const checkoutPageComplete = require('../pageobjects/checkout.page.complete')

describe('Valid checkout', () => {
    it('Checkout should work properly', async () => {
        await loginPage.open()
        await loginPage.inputUsername.addValue('standard_user')
        await loginPage.inputPassword.addValue('secret_sauce')
        await loginPage.btnLogin.click()
        await inventoryPage.btnAddToCartBackpack.click()
        await inventoryPage.btnMenu.click()
        await inventoryPage.btnLogout.click()
        await loginPage.inputUsername.addValue('standard_user')
        await loginPage.inputPassword.addValue('secret_sauce')
        await loginPage.btnLogin.click()
        await inventoryPage.btnCart.click()
        await expect(browser).toHaveUrl('https://www.saucedemo.com/cart.html')
        await expect(cartPage.textItemNameList[0]).toBeDisplayed()
        await expect(cartPage.textItemNameList[0]).toHaveText('Sauce Labs Backpack')
        await cartPage.btnCOUT.click()
        await checkoutPage.inputFirstName.addValue('Standard')
        await checkoutPage.inputLastName.addValue('User')
        await checkoutPage.inputZIP.addValue('33333')
        await checkoutPage.btnContinue.click()
        await checkoutPage2.btnFinish.click()
        await checkoutPageComplete.btnHome.click()
        await expect(inventoryPage.badgeCart).not.toBeExisting()
    })
})